version: "3.9"
services:
  ansible:
    build:
      context: .
    image: solarbx-config
    volumes:
      - ./ansible.cfg:/ansible/ansible.cfg
      - ./files:/ansible/files
      - ./inventory:/ansible/inventory
      - ./playbooks:/ansible/playbooks
      - ./roles:/ansible/roles
      - ~/.ssh:/root/.ssh:ro
    environment:
      - ANSIBLE_CONFIG=/ansible/ansible.cfg
    entrypoint: ["/bin/bash"]
